my_site/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('catalog/', views.catalog, name='catalog'),
    path('catalog/<int:catalog>/', views.catalog, name='catalog_by_category'),
    path('product/<int:product>', views.product_detail, name='product')
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

saints_planet/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('my_site.urls')),
    path('admin/', admin.site.urls),
]

my_site/models.py
from django.db import models as django_models
from django.urls import reverse
from mptt import models as mptt_models


# Create your models here.
class Catalog(mptt_models.MPTTModel):
    name = django_models.CharField(max_length=1024)
    parent = mptt_models.TreeForeignKey('self', null=True, blank=True, related_name='children', on_delete=django_models.CASCADE)

    class MPTTMeta:
        order_insertions_by = ['name']

    def __str__(self):
        return f'Категория {self.name}'

    def get_absolute_url(self):
        return reverse('catalog_by_category', args=[self.id])


class Product(django_models.Model):
    class Sex(django_models.TextChoices):
        MEN = ('M', 'Для мужчин')
        WOMEN = ('W', 'Для женщин')
        UNISEX = ('U', 'Унисекс')
        NONE = ('N', 'Не указано')

    catalog = django_models.ForeignKey(Catalog, on_delete=django_models.CASCADE)
    name = django_models.CharField(max_length=1024)
    stock = django_models.PositiveIntegerField()
    description = django_models.TextField()
    price = django_models.DecimalField(max_digits=10, decimal_places=2)
    discount = django_models.IntegerField()
    sex = django_models.CharField(max_length=1, choices=Sex.choices)
    sold = django_models.PositiveIntegerField()

    def price_with_discount(self):
        return self.price * (100 - self.discount) / 100

    def __str__(self):
        return f'{self.name}'

    def get_absolute_url(self):
        return reverse('product', args=[self.id])


class ProductImage(django_models.Model):
    product = django_models.ForeignKey(Product, on_delete=django_models.CASCADE)
    image = django_models.ImageField()

    def __str__(self):
        return f'{self.image.name}'


class Characteristic(django_models.Model):
    name = django_models.CharField(max_length=1024)
    catalog = django_models.ForeignKey(Catalog, on_delete=django_models.CASCADE)

    def __str__(self):
        return f'Характеристика {self.name}'


class CharacteristicValue(django_models.Model):
    characteristic = django_models.ForeignKey(Characteristic, on_delete=django_models.CASCADE)
    value = django_models.CharField(max_length=1024)

    def __str__(self):
        return f'Значение {self.value} - {self.characteristic}'

my_site/views.py
from django.http import HttpResponse
from django.shortcuts import get_object_or_404
from django.template import loader

from .models import Product, Catalog


# Create your views here.


def index(request):
    template = loader.get_template('my_site/index.html')
    bestsellers = Product.objects.order_by('sold')

    tShirts = Product.objects.filter(catalog__name__startswith='Рубашки')

    shoes = Product.objects.filter(catalog__name__startswith='Обувь')

    context = {
        'bestsellers': bestsellers,
        'tShirts': tShirts,
        'shoes': shoes,
    }
    return HttpResponse(template.render(request=request, context=context))


def catalog(request, catalog=None):
    template = loader.get_template('my_site/catalog.html')
    context = {'categories': Catalog.objects.all()}
    if catalog:
        context['current_category'] = get_object_or_404(Catalog, pk=catalog)

        if context['current_category']:
            context['products'] = context['current_category'].product_set.all()

    return HttpResponse(template.render(request=request, context=context))


def product_detail(request, product):
    template = loader.get_template('my_site/product.html')
    context = {'product': get_object_or_404(Product, pk=product)}
    return HttpResponse(template.render(request=request, context=context))

my_site/templates/my_site/FAQ.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset="utf-8"">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> basket</title>
    <link rel="stylesheet" href="css/main.css">
    <link rel="stylesheet" href="css/FAQ.css">
  </head>
  <body>

    <nav class="navbar"> <!--навигация-->
      </nav>

  <script type="text/javascript" src="js/home.js"></script>



  </body>
</html>

my_site/templates/my_site/catalog.html
{% extends 'base.html' %}
{% load static %}
{% load mptt_tags %}

{% block additional_css %}
    <link rel="stylesheet" href="{% static 'my_site/css/catalog.css' %}">
{% endblock %}
{% block main %}
    <section class="author-archive">
        <div class="container">
            <h1>
                {% if curent_category %}
                    {{ curent_category.name }}
                {% else %}
                    Каталог
                {% endif %}
            </h1>
            <div class="wrapper">
                <ol class="filters">
                    {% recursetree categories %}
                        <li>
                            <label>
                                <a href="{{ node.get_absolute_url }}">{{ node.name }}</a>
                                {% if not node.is_leaf_node %}
                                    <ol class="children">
                                        <a href="{{ children.get_absolute_url }}">{{ children }}</a>
                                    </ol>
                                {% endif %}
                            </label>
                        </li>
                    {% endrecursetree %}

                </ol>

                <ol class="posts">
                    {% for product in products %}
                        <li class="post">
                            <article>
                                <figure>
                                    <a href="{{ product.get_absolute_url }}">
                                        <div class="product-image">
                                            {% if product.discount > 0 %}
                                                <span class="discount-tag">{{ product.discount }}% Скидка</span>
                                            {% endif %}
                                            <img src="{{ product.productimage_set.first.image.url }}"
                                                 class="product-thumb" alt="">
                                            {#                                        <button class="card-btn">Добавить в список желаемого</button>#}
                                        </div>
                                    </a>
                                    <figcaption>
                                        <h2 class="post-title">
                                            <div class="product-info">
                                                <h4 class="product-brand">{{ product.name }}</h4>
                                                <span class="price">{{ product.price_with_discount }}₽</span><span
                                                    class="actual-price">{{ product.price }}₽</span>
                                            </div>
                                        </h2>
                                    </figcaption>
                                </figure>
                            </article>
                        </li>
                    {% endfor %}
                </ol>
            </div>
        </div>
    </section>
{% endblock %}

my_site/templates/my_site/form_authorization.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>

    <meta http-equiv="Content-Type" content="text/html; charset="utf-8"">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Авторизазия</title>

    <link rel="stylesheet" href="css/main.css">
    <link rel="stylesheet" href="css/footer.css">
    <link rel="stylesheet" href="css/form_authorization.css">

  </head>
  <body>

    <nav class="navbar"> <!--Хотелось бы блоки накинуть через жабаскрипт но он не работает( --><!--навигация-->

      <div class="nav">
        <img src="img/dark-logo.png" class="brand-logo" alt="">
        <div class="nav-items">
            <div class="search">
                <input type="text" class="search-box" placeholder="Поиск по бренду, товару...">
                <button class="search-btn">Поиск</button>
            </div>
            <a href="#"><img src="img/user.png" alt=""></a>
            <a href="#"><img src="img/cart.png" alt=""></a>
        </div>
      </div>
      <ul class="links-container">
          <li class="link-item"><a href="#" class="link">Главная</a></li>
          <li class="link-item"><a href="#" class="link">Женское</a></li>
          <li class="link-item"><a href="#" class="link">Мужское</a></li>
          <li class="link-item"><a href="#" class="link">Дети</a></li>
          <li class="link-item"><a href="#" class="link">Аксесуары</a></li>
      </ul>

    </nav>

    <div class="form_auth_block">
      <div class="form_auth_block_content">
        <p class="form_auth_block_head_text">Авторизация</p>
      <form class="form_auth_style" action="#" method="post">
          <input type="email" name="auth_email" placeholder="Введите Ваш имейл" required >
          <input type="password" name="auth_pass" placeholder="Введите пароль" required >
          <button class="form_auth_button" type="submit" name="form_auth_submit">Войти</button>
      </form>
    </div>
  </div>

    <footer>
      <div class="footer-content">
          <img src="img/light-logo.png" class="logo" alt="">
          <div class="footer-ul-container">
              <ul class="category">
                  <li class="category-title">Мужское</li>
                  <li><a href="#" class="footer-link">футболки</a></li>
                  <li><a href="#" class="footer-link">толстовки</a></li>
                  <li><a href="#" class="footer-link">рубашки</a></li>
                  <li><a href="#" class="footer-link">джинсы</a></li>
                  <li><a href="#" class="footer-link">брюки</a></li>
                  <li><a href="#" class="footer-link">обувь</a></li>
                  <li><a href="#" class="footer-link">Кэжуал</a></li>
                  <li><a href="#" class="footer-link">официальная одежда</a></li>
                  <li><a href="#" class="footer-link">спорт</a></li>
                  <li><a href="#" class="footer-link">часы</a></li>
              </ul>
              <ul class="category">
                  <li class="category-title">Женское</li>
                  <li><a href="#" class="footer-link">футболки</a></li>
                  <li><a href="#" class="footer-link">толстовки</a></li>
                  <li><a href="#" class="footer-link">рубашки</a></li>
                  <li><a href="#" class="footer-link">джинсы</a></li>
                  <li><a href="#" class="footer-link">брюки</a></li>
                  <li><a href="#" class="footer-link">обувь</a></li>
                  <li><a href="#" class="footer-link">Кэжуал</a></li>
                  <li><a href="#" class="footer-link">официальная одежда</a></li>
                  <li><a href="#" class="footer-link">спорт</a></li>
                  <li><a href="#" class="footer-link">часы</a></li>
              </ul>
          </div>
      </div>

      <!-- предыдущие элементы -->
      <p class="footer-title">О КОМПАНИИ</p>
      <p class="info">Дом - это наши клиенты. Ваше время, чтобы доставить их ей в любое время, но вариант только спросить, который создает структуру и большую часть настоящего, мастер-строитель миниатюр отвергает это оригинальное взятие других мужчин. Эти инструменты ненавидят больше всего, что удовольствие от танца связанного тела! Когда ошибка сама по себе перекусывает время в реальном мире, нуждается в наших способах! Долги по его получению никто не откроет, кроме как, и донесет на службы. Закуски, которые упражняются, когда вина очаровывает город, различие во времени, желание присутствующих, кроме как в качестве постоянного, принимая легкое удовольствие от бегства от этого удовольствия для него. Аспериорес, родился! Является ли первоначальный инцидент таким, чтобы понравиться всем, поэтому один из них?</p>
      <p class="info">Email поддержки - help@poderjka.com</p>
      <p class="info">телефон - +7 999 212 85 06</p>
      <div class="footer-social-container">
          <div>
              <a href="#" class="social-link">условия и услуги</a>
              <a href="#" class="social-link">Конфиденциальность</a>
          </div>
          <div>
              <a href="#" class="social-link">instagram</a>
              <a href="#" class="social-link">facebook</a>
              <a href="#" class="social-link">twitter</a>
          </div>
      </div>
      <p class="footer-credit">Интернет-магазин лучшей одежды</p>

  </footer>

  </body>
</html>

my_site/templates/my_site/index.html
{% extends 'base.html' %}
{% load static %}

{% block additional_css %}
    <link rel="stylesheet" href="{% static 'my_site/css/product.css' %}">
{% endblock %}

{% block main %}
    <header class="hero-section"> <!--заголовок+фон-->
        <div class="content">
            <img src="{% static 'my_site/img/light-logo.png' %}" class="logo" alt="">
            <p class="sub-heading">best fashion collection of all time</p>
        </div>
    </header>

    <section class="product"> <!-- cards container -->
        <!-- СЛАЙДЕР -->

        <h2 class="product-category"> Топ продаж </h2>
        <!-- Кнопки слайдеры -->
        <button class="pre-btn"><img src="{% static 'my_site/img/arrow.png' %}" alt=""></button>
        <button class="nxt-btn"><img src="{% static 'my_site/img/arrow.png' %}" alt=""></button>
        <div class="product-container">

            {% for product in bestsellers %}
                <div class="product-card"> <!-- 1я карта -->
                    <div class="product-image">
                        {% if product.discount > 0 %}
                            <span class="discount-tag">{{ product.discount }} Скидка</span>
                        {% endif %}
                        <img src="{{ product.productimage_set.first.image.url }}" class="product-thumb" alt="">
                        {#                    <button class="card-btn">Добавить в список желаемого</button>#}
                    </div>
                    <div class="product-info">
                        <h2 class="product-brand">{{ product.name }}</h2>
                        <p class="product-short-des">{{ product.description }}</p>
                        <span class="price">{{ product.price_with_discount }}₽</span><span
                            class="actual-price">{{ product.price }}₽</span>
                    </div>
                </div>
            {% endfor %}

        </div>

    </section>

    <section class="collection-container"> <!-- Коллекции  -->
        <a href="#" class="collection">
            <img src="{% static 'my_site/img/women-collection.png' %}" alt="">
            <p class="collection-title">Женская <br> одежда</p>
        </a>
        <a href="#" class="collection">
            <img src="{% static 'my_site/img/men-collection.png' %}" alt="">
            <p class="collection-title">Мужская <br> одежда</p>
        </a>
        <a href="#" class="collection">
            <img src="{% static 'my_site/img/accessories-collection.png' %}" alt="">
            <p class="collection-title">Аксесуары</p>
        </a>
    </section>

    <section class="product"> <!-- cards container -->
        <!-- СЛАЙДЕР -->

        <h2 class="product-category">Рубашки</h2>
        <!-- Кнопки слайдеры -->
        <button class="pre-btn"><img src="{% static 'my_site/img/arrow.png' %}" alt=""></button>
        <button class="nxt-btn"><img src="{% static 'my_site/img/arrow.png' %}" alt=""></button>
        <div class="product-container">

            {% for product in tShirts %}
                <div class="product-card"> <!-- 1я карта -->
                    <div class="product-image">
                        {% if product.discount > 0 %}
                            <span class="discount-tag">{{ product.discount }} Скидка</span>
                        {% endif %}
                        <img src="{{ product.productimage_set.first.image.url }}" class="product-thumb" alt="">
                        {#                    <button class="card-btn">Добавить в список желаемого</button>#}
                    </div>
                    <div class="product-info">
                        <h2 class="product-brand">{{ product.name }}</h2>
                        <p class="product-short-des">{{ product.description }}</p>
                        <span class="price">{{ product.price_with_discount }}₽</span><span
                            class="actual-price">{{ product.price }}₽</span>
                    </div>
                </div>
            {% endfor %}

        </div>


    </section>

    <section class="product"> <!-- cards container -->
        <!-- СЛАЙДЕР -->

        <h2 class="product-category"> Обувь </h2>
        <!-- Кнопки слайдеры -->
        <button class="pre-btn"><img src="{% static 'my_site/img/arrow.png' %}" alt=""></button>
        <button class="nxt-btn"><img src="{% static 'my_site/img/arrow.png' %}" alt=""></button>
        <div class="product-container">

            {% for product in shoes %}
                <div class="product-card"> <!-- 1я карта -->
                    <div class="product-image">
                        {% if product.discount > 0 %}
                            <span class="discount-tag">{{ product.discount }} Скидка</span>
                        {% endif %}
                        <img src="{{ product.productimage_set.first.image.url }}" class="product-thumb" alt="">
                        {#                    <button class="card-btn">Добавить в список желаемого</button>#}
                    </div>
                    <div class="product-info">
                        <h2 class="product-brand">{{ product.name }}</h2>
                        <p class="product-short-des">{{ product.description }}</p>
                        <span class="price">{{ product.price_with_discount }}₽</span><span
                            class="actual-price">{{ product.price }}₽</span>
                    </div>
                </div>
            {% endfor %}

        </div>

    </section>

{% endblock %}

my_site/templates/my_site/product.html
{% extends 'base.html' %}
{% load static %}
{% block additional_css %}
    <link rel="stylesheet" href="{% static 'my_site/css/product.css' %}">
{% endblock %}
{% block main %}


    <section class="product-details">
        <div class="image-slider">
            <div class="product-images">
                {% for image in product.productimage_set.all %}
                    <img src="{{ image.image.url }}" class="
                    {% if forloop..first %}
                        active
                    {% endif %}
                " alt="">
                {% endfor %}
            </div>
        </div>
        <div class="details">
            <h2 class="product-brand">{{ product.name }}</h2>
            <p class="product-short-des">{{ product.description }}</p>
            <span class="product-price">{{ product.price_with_discount }}₽</span>
            <span class="product-actual-price">{{ product.price }}₽</span>
            {% if product.discount > 0 %}
                <span class="product-discount">( {{ product.discount }}% скидка )</span>
            {% endif %}
            <p class="product-sub-heading">выберите размер</p>

            <input type="radio" name="size" value="s" checked hidden id="s-size">
            <label for="s-size" class="size-radio-btn check">s</label>
            <input type="radio" name="size" value="m" hidden id="m-size">
            <label for="m-size" class="size-radio-btn">m</label>
            <input type="radio" name="size" value="l" hidden id="l-size">
            <label for="l-size" class="size-radio-btn">l</label>
            <input type="radio" name="size" value="xl" hidden id="xl-size">
            <label for="xl-size" class="size-radio-btn">xl</label>
            <input type="radio" name="size" value="xxl" hidden id="xxl-size">
            <label for="xxl-size" class="size-radio-btn">xxl</label>

            <button class="btn cart-btn">добавить в корзину</button>
        </div>
    </section>

{% endblock %}
{% block additional_js %}
    <script src="{% static 'my_site/js/product.js' %}"></script>
{% endblock %}

my_site/templates/my_site/search.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>search</title>
    <link rel="stylesheet" href="css/main.css">
    <link rel="stylesheet" href="css/search.css">
  </head>
  <body>
    <nav class="navbar">
      <div class="nav">
        <img src="img/dark-logo.png" class="brand-logo" alt="">
        <div class="nav-items">
            <div class="search">
                <input type="text" class="search-box" placeholder="Поиск по бренду, товару...">
                <button class="search-btn">Поиск</button>
            </div>
            <a href="#"><img src="img/user.png" alt=""></a>
            <a href="#"><img src="img/cart.png" alt=""></a>
        </div>
      </div>
      <ul class="links-container">
          <li class="link-item"><a href="#" class="link">Главная</a></li>
          <li class="link-item"><a href="#" class="link">Женское</a></li>
          <li class="link-item"><a href="#" class="link">Мужское</a></li>
          <li class="link-item"><a href="#" class="link">Дети</a></li>
          <li class="link-item"><a href="#" class="link">Аксесуары</a></li>
      </ul>
    </nav>

      <section class="search-results">
        <h2 class="heading"><span>Товары</span> по вашему запросу</h2>
    </section>

    <footer>
      <div class="footer-content">
          <img src="img/light-logo.png" class="logo" alt="">
          <div class="footer-ul-container">
              <ul class="category">
                  <li class="category-title">Мужское</li>
                  <li><a href="#" class="footer-link">футболки</a></li>
                  <li><a href="#" class="footer-link">толстовки</a></li>
                  <li><a href="#" class="footer-link">рубашки</a></li>
                  <li><a href="#" class="footer-link">джинсы</a></li>
                  <li><a href="#" class="footer-link">брюки</a></li>
                  <li><a href="#" class="footer-link">обувь</a></li>
                  <li><a href="#" class="footer-link">Кэжуал</a></li>
                  <li><a href="#" class="footer-link">официальная одежда</a></li>
                  <li><a href="#" class="footer-link">спорт</a></li>
                  <li><a href="#" class="footer-link">часы</a></li>
              </ul>
              <ul class="category">
                  <li class="category-title">Женское</li>
                  <li><a href="#" class="footer-link">футболки</a></li>
                  <li><a href="#" class="footer-link">толстовки</a></li>
                  <li><a href="#" class="footer-link">рубашки</a></li>
                  <li><a href="#" class="footer-link">джинсы</a></li>
                  <li><a href="#" class="footer-link">брюки</a></li>
                  <li><a href="#" class="footer-link">обувь</a></li>
                  <li><a href="#" class="footer-link">Кэжуал</a></li>
                  <li><a href="#" class="footer-link">официальная одежда</a></li>
                  <li><a href="#" class="footer-link">спорт</a></li>
                  <li><a href="#" class="footer-link">часы</a></li>
              </ul>
          </div>
      </div>

      <!-- предыдущие элементы -->
      <p class="footer-title">О КОМПАНИИ</p>
      <p class="info">Дом - это наши клиенты. Ваше время, чтобы доставить их ей в любое время, но вариант только спросить, который создает структуру и большую часть настоящего, мастер-строитель миниатюр отвергает это оригинальное взятие других мужчин. Эти инструменты ненавидят больше всего, что удовольствие от танца связанного тела! Когда ошибка сама по себе перекусывает время в реальном мире, нуждается в наших способах! Долги по его получению никто не откроет, кроме как, и донесет на службы. Закуски, которые упражняются, когда вина очаровывает город, различие во времени, желание присутствующих, кроме как в качестве постоянного, принимая легкое удовольствие от бегства от этого удовольствия для него. Аспериорес, родился! Является ли первоначальный инцидент таким, чтобы понравиться всем, поэтому один из них?</p>
      <p class="info">Email поддержки - help@poderjka.com</p>
      <p class="info">телефон - +7 999 212 85 06</p>
      <div class="footer-social-container">
          <div>
              <a href="#" class="social-link">условия и услуги</a>
              <a href="#" class="social-link">Конфиденциальность</a>
          </div>
          <div>
              <a href="#" class="social-link">instagram</a>
              <a href="#" class="social-link">facebook</a>
              <a href="#" class="social-link">twitter</a>
          </div>
      </div>
      <p class="footer-credit">Интернет-магазин лучшей одежды</p>
    </footer>



  </body>
</html>

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ru" dir="ltr">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> Online store</title>
    <link rel="stylesheet" href="{% static 'my_site/css/main.css' %}">
    {% block additional_css %}

    {% endblock %}

</head>
<body>

<nav class="navbar"> <!--навигация-->

    <div class="nav">
        <img src="{% static 'my_site/img/dark-logo.png' %}" class="brand-logo" alt="">
        <div class="nav-items">
            <div class="search">
                <!--suppress HtmlFormInputWithoutLabel -->
                <input type="text" class="search-box" placeholder="Поиск по бренду, товару...">
                <button class="search-btn">Поиск</button>
            </div>
            <a href="#"><img src="{% static 'my_site/img/user.png' %}" alt=""></a>
            <a href="#"><img src="{% static 'my_site/img/cart.png' %}" alt=""></a>
        </div>
    </div>
    <ul class="links-container">
        <li class="link-item"><a href="{% url 'index' %}" class="link">Главная</a></li>
        <li class="link-item"><a href="#" class="link">Женское</a></li>
        <li class="link-item"><a href="#" class="link">Мужское</a></li>
        <li class="link-item"><a href="#" class="link">Дети</a></li>
        <li class="link-item"><a href="#" class="link">Аксесуары</a></li>
    </ul>

</nav>
{% block main %}

{% endblock %}
<footer>
    <div class="footer-content">
        <img src="{% static 'my_site/img/light-logo.png' %}" class="logo" alt="">
        <div class="footer-ul-container">
            <ul class="category">
                <li class="category-title">Мужское</li>
                <li><a href="#" class="footer-link">футболки</a></li>
                <li><a href="#" class="footer-link">толстовки</a></li>
                <li><a href="#" class="footer-link">рубашки</a></li>
                <li><a href="#" class="footer-link">джинсы</a></li>
                <li><a href="#" class="footer-link">брюки</a></li>
                <li><a href="#" class="footer-link">обувь</a></li>
                <li><a href="#" class="footer-link">Кэжуал</a></li>
                <li><a href="#" class="footer-link">официальная одежда</a></li>
                <li><a href="#" class="footer-link">спорт</a></li>
                <li><a href="#" class="footer-link">часы</a></li>
            </ul>
            <ul class="category">
                <li class="category-title">Женское</li>
                <li><a href="#" class="footer-link">футболки</a></li>
                <li><a href="#" class="footer-link">толстовки</a></li>
                <li><a href="#" class="footer-link">рубашки</a></li>
                <li><a href="#" class="footer-link">джинсы</a></li>
                <li><a href="#" class="footer-link">брюки</a></li>
                <li><a href="#" class="footer-link">обувь</a></li>
                <li><a href="#" class="footer-link">Кэжуал</a></li>
                <li><a href="#" class="footer-link">официальная одежда</a></li>
                <li><a href="#" class="footer-link">спорт</a></li>
                <li><a href="#" class="footer-link">часы</a></li>

            </ul>
        </div>
    </div>

    <!-- предыдущие элементы -->
    <p class="footer-title">О КОМПАНИИ</p>
    <p class="info">Дом - это наши клиенты. Ваше время, чтобы доставить их ей в любое время, но вариант только спросить,
        который создает структуру и большую часть настоящего, мастер-строитель миниатюр отвергает это оригинальное
        взятие других мужчин. Эти инструменты ненавидят больше всего, что удовольствие от танца связанного тела! Когда
        ошибка сама по себе перекусывает время в реальном мире, нуждается в наших способах! Долги по его получению никто
        не откроет, кроме как, и донесет на службы. Закуски, которые упражняются, когда вина очаровывает город, различие
        во времени, желание присутствующих, кроме как в качестве постоянного, принимая легкое удовольствие от бегства от
        этого удовольствия для него. Аспериорес, родился! Является ли первоначальный инцидент таким, чтобы понравиться
        всем, поэтому один из них?</p>
    <p class="info">Email поддержки - help@poderjka.com</p>
    <p class="info">телефон - +7 999 212 85 06</p>
    <div class="footer-social-container">
        <div>
            <a href="#" class="social-link">условия и услуги</a>
            <a href="#" class="social-link">Конфиденциальность</a>
        </div>
        <div>
            <a href="#" class="social-link">instagram</a>
            <a href="#" class="social-link">facebook</a>
            <a href="#" class="social-link">twitter</a>
        </div>
    </div>
    <p class="footer-credit">Интернет-магазин лучшей одежды</p>

</footer>

{% block additional_js %}
    <script type="text/javascript" src="{% static 'my_site/js/product.js' %}"></script>
    <script type="text/javascript" src="{% static 'my_site/js/home.js' %}"></script>
{% endblock %}

</body>
</html>